### ISSUE TITLE
Separation 

### ISSUE THREAD

**Issue by Taurean75** [bobbyrne01/local-music-player-firefox#10]
Hello --

It would be nicer if you'd separate the player and the list of songs.  As it is now, you'd have to scroll up and down to see the seek bar.

Thanks!

M

**Comment by bobbyrne01** [comment]
@Taurean75 great idea!

Something like this? http://jsfiddle.net/bobbyrne01/hh8ysd4e/1/

**Comment by Taurean75** [comment]
Yup, just like that! :)

About the play button, it should check if the filter was trigger; if it has, it should play the first song on the filtered list. Also, could you make it remember the filter words?

Thanks.

**Comment by bobbyrne01** [comment]
Separate scroller delivered in [0.8.2](https://github.com/bobbyrne01/local-music-player-firefox/releases/tag/0.8.2)

I've opened #12 to track "About the play button, it should check if the filter was triggered; if it has, it should play the first song on the filtered list."

For "remember the filter words", how do you expect that to work .. Currently, the filtering is applied every-time a key is pressed, 
 - do you want to store every variation of key presses? It could be a very large list.
 - or have a save button so you can choose which words to save?

**Comment by bobbyrne01** [comment]
closing as separation is available in [0.8.2](https://github.com/bobbyrne01/local-music-player-firefox/releases/tag/0.8.2)
