### ISSUE TITLE
Control box added instead of tooltip text

### ISSUE THREAD

**Issue by elmo88** [bobbyrne01/local-music-player-firefox#18]
Would be pretty nice if when the cursor hovers over the icon, it came up with a small control box that had forward, back, stop, pause, would save the need to have to open the whole UI every time you wanted to change a track......just a thought, you can delete this issue if you like.

**Comment by bobbyrne01** [comment]
Nice idea @elmo88 

The firefox addon sdk doesn't provide an easy way to detect `actionButton.onHover()`, only `actionButton.onClick()` currently.

Looking around the different UI objects firefox exposes though, I see `toolbars`, which might be a perfect fit for the addon (see image below code snippet) e.g https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/ui#Toolbar

The `toolbar` would be:
 * optional
 * consume minimal screen space, basically the buttons you suggested

**Comment by elmo88** [comment]
Yeah well look dude it's your decision, just throwing out ideas, but I think that would be very beneficial. If it can be done great, if not maybe just reduce the screen size cos it takes up a lot of space at the moment. 
Date: Mon, 26 Jan 2015 10:38:32 -0800

**Comment by bobbyrne01** [comment]
feature delivered in [0.10.1](https://github.com/bobbyrne01/local-music-player-firefox/releases/tag/0.10.1)

![selection_015](https://cloud.githubusercontent.com/assets/1746110/5994496/13c896ca-aa6e-11e4-9447-9fad1b15dd61.png)

![selection_016](https://cloud.githubusercontent.com/assets/1746110/5994498/1d61ab54-aa6e-11e4-9235-5edd1cf8212a.png)

**Comment by elmo88** [comment]
Good work dude!! Works like a charm, one tiny suggestion though, you're missing the shuffle button, in my opinion the single most useful thing on any music player! Nice song choice by the way, I've been rocking that album recently. On a different subject altogether Ali and Andy's engagement party is on valentine's day in the shamrock if you and your lady friend are interested?

Date: Sun, 1 Feb 2015 15:58:15 -0800

**Comment by bobbyrne01** [comment]
Random button added to toolbar in [0.10.3](https://github.com/bobbyrne01/local-music-player-firefox/releases/tag/0.10.3), should be available from Mozilla within a day or two.

Screenshot ..

![selection_023](https://cloud.githubusercontent.com/assets/1746110/6011473/2358b856-ab34-11e4-8b0f-2f59c03ac135.png)
