### ISSUE TITLE
Ability to toggle showing or hiding of the toolbar with hotkeys

### ISSUE THREAD

**Issue by dillbyrne** [bobbyrne01/local-music-player-firefox#23]
Keep up the good work @bobbyrne01 :+1:

**Comment by bobbyrne01** [comment]
Thanks! 

Showing and hiding the toolbar programmatically isn't available yet in [addon sdk](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_toolbar), but I'll leave this open for awhile since functionality might be added soon to the *experimental* module.

**Comment by bobbyrne01** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1130184

**Comment by dillbyrne** [comment]
@bobbyrne01 Thanks for the update. The only way I can think of to add this would be to create and destroy the panel each time and preserve the state while it is destroyed. I had to do something similar for a context menu before. Anyone I'm not too pushed for it so I'll close this now.
