### ISSUE TITLE
FFv.37.0.2   LMPv.0.11.0      Not work buttons, repeat etc

### ISSUE THREAD

**Issue by osminogig** [bobbyrne01/local-music-player-firefox#25]
Good addition, but doesn't work

**Comment by bobbyrne01** [comment]
just tested this on a new profile and buttons are working for me on ff37.0.2

@osminogig you referring to the toolbar buttons or panel?

**Comment by osminogig** [comment]
Profile almost pure, but later I will check on absolutely pure profile. (FF(ru)portableapps)
Don't work neither in a popup window nor at the panel.

**Comment by osminogig** [comment]
Hi ! Excuse my English. I made video and SystemInfoSnapshot.
Now I used it  pcxFirefox-37.0.1-enUS-vc2013-x86-sse2-betterpgo-150403 (not portable mode)
Didn't help.

I wish good luck to your wonderful addition !
__________________________________________________
https://www.dropbox.com/s/itd8shx31b13zrz/Video_2015-05-03_171402.wmv?dl=0
https://www.dropbox.com/s/zyji2246qoujfl8/SystemInfoSnapshot_03.05.2015_17-21-14.html?dl=0

**Comment by osminogig** [comment]
It is f. magic !
I established it    https://download.mozilla.org/?product=firefox-37.0.2-SSL&os=win&lang=en-US
Everything perfectly works!
I will experiment further...

**Comment by osminogig** [comment]
It is f. magic !
I established it    https://download.mozilla.org/?product=firefox-37.0.2-SSL&os=win&lang=en-US
Everything perfectly works!
I will experiment further...

**Comment by osminogig** [comment]
Hi ! Excuse my English. I made video.
Now I used it pcxFirefox-37.0.1-enUS-vc2013-x86-sse2-betterpgo-150403 (not portable mode)
Didn't help.
I wish good luck to your wonderful addition !
https://www.dropbox.com/s/itd8shx31b13zrz/Video_2015-05-03_171402.wmv?dl=0
(better download it)
_______________________________________________________

ROFL !!!!!!!!!!!!
Simply specific files got to me !
I think you might want to look at them, and the music is good :
https://www.dropbox.com/s/x50frslfxue39h1/DArk%26ChBr%28015%29.zip?dl=0
If you understand what to do. Please let us know.
Thanks for the beutiful addon !
