### ISSUE TITLE
Doesn't work on mac

### ISSUE THREAD

**Issue by independentwalrus** [bobbyrne01/local-music-player-firefox#28]
Love to use this addon but the audio doesn't seem to work. The libraries loaded fine and it makes every indication that its working but no sound. I tried testing a short track to see if it would play and go to the next one and it doesn't. Also it doesn't show the top bar for the time ticker of the song (or the volume).

**Comment by bobbyrne01** [comment]
ill check this out on a mac and get back to you ..

**Comment by independentwalrus** [comment]
Thanks!

**Comment by RomanADavis** [comment]
Having the same issue on Windows 7. :(  Do you plan on maintaining this in the future?

**Comment by bobbyrne01** [comment]
Issue on windows10 for me too. Will look into it.

**Comment by RomanADavis** [comment]
Thank you~! This seems like that one last thing that would make firefox perfect.
