### ISSUE TITLE
Not working on Linux Firefox-45.0.1

### ISSUE THREAD

**Issue by cavalier911** [bobbyrne01/local-music-player-firefox#29]
Status bar doesn't advance, no sound. Tested using mp3 and ogg files that play if opened in firefox with File/Open File. Now that firefox on linux can play many formats by just installing ffmpeg this add-on would be very useful. Please contact if you need additional info.

**Comment by gaul** [comment]
Not working on Mac OS X Firefox 50.0b2 with e10s enabled.
